#!/usr/bin/env bash
#
# Turns whatever a maintenance routine committed into a pull request.
#
# The routine commits locally on a `claude/maint-*` branch and writes the PR
# title and body to .maintenance/pr-body.md (first line title, blank line, then
# body). Pushing and opening the PR happens here instead of inside the agent so
# that "the routine found nothing" is the boring default: no commit means no
# branch, no PR, and a clean exit.
set -euo pipefail

DEFAULT_BRANCH="${DEFAULT_BRANCH:-main}"
BODY_FILE=".maintenance/pr-body.md"

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "HEAD" ]; then
  echo "Detached HEAD — the routine did not create a branch. Nothing to open."
  exit 0
fi

if [ "$branch" = "$DEFAULT_BRANCH" ]; then
  echo "Still on $DEFAULT_BRANCH — the routine made no commit. Nothing to open."
  exit 0
fi

case "$branch" in
  claude/maint-*) ;;
  *)
    echo "Refusing to push '$branch': maintenance branches must be claude/maint-*." >&2
    exit 1
    ;;
esac

ahead="$(git rev-list --count "origin/${DEFAULT_BRANCH}..HEAD")"
if [ "$ahead" -eq 0 ]; then
  echo "Branch $branch has no commits ahead of $DEFAULT_BRANCH. Nothing to open."
  exit 0
fi

if [ ! -s "$BODY_FILE" ]; then
  echo "Branch $branch has $ahead commit(s) but no $BODY_FILE." >&2
  echo "The routine must describe its change before it can be reviewed." >&2
  exit 1
fi

title="$(head -n 1 "$BODY_FILE")"
body="$(tail -n +2 "$BODY_FILE")"

if [ -z "$title" ]; then
  echo "$BODY_FILE has an empty first line; expected the PR title there." >&2
  exit 1
fi

for attempt in 1 2 3 4; do
  if git push -u origin "$branch"; then
    break
  fi
  if [ "$attempt" -eq 4 ]; then
    echo "Push failed after 4 attempts." >&2
    exit 1
  fi
  sleep $((2 ** attempt))
done

printf '%s\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_\n' \
  "$body" > /tmp/maintenance-pr-body.md

gh pr create \
  --base "$DEFAULT_BRANCH" \
  --head "$branch" \
  --title "$title" \
  --body-file /tmp/maintenance-pr-body.md

echo "Opened PR from $branch"
